#ifndef MODIFICARUSUARIOSSOPORTECLIENTE_H_INCLUDED
#define MODIFICARUSUARIOSSOPORTECLIENTE_H_INCLUDED
#include "usuarios.h"

void menuModificarUsrSoporte(Usuario &usrlog);

#endif // MODIFICARUSUARIOSSOPORTECLIENTE_H_INCLUDED
